### ISSUE TITLE
Suggestions for working with expanded package patterns?

### ISSUE THREAD

**Issue by webframp** [FiloSottile/homebrew-gomod#1]
Hey @FiloSottile thanks for this, much cleaner install method for managing local go installed tools. 

A few things I use such as https://github.com/cweill/gotests default to an expanded path install method such as:

```
$ go get -u github.com/cweill/gotests/...
```

What do you recommend for installing these with `gomod`? Right now it just throws the following:

```
go: malformed import path "gomod-.../2020-04-21": trailing dot in path element
```

**Comment by FiloSottile** [comment]
I really need to rewrite this as a proper Go program that uses `go list` to get the real version, etc. but in the meantime I'll just strip `/...` when picking the short name.

**Comment by FiloSottile** [comment]
Should be available via `brew upgrade`! Let me know if it works :)

**Comment by webframp** [comment]
Can confirm. That works well for now, thanks!
